name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '18'

    - name: Spring boot build Gradle
      run: ./gradlew build

    - name: Build file copy
      run: cp build/libs/sampleApp-0.0.1-SNAPSHOT.jar .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: build and release to DockerHub
      env:
        NAME: fails12 # 계정 명
        REPO: cloudnative-sample

      # 레포 이름
      run: |
        docker build . --file Dockerfile --tag $REPO:latest
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest

